title: Aussies against the Loan Charge
email: "AussiesResistingHMRC@gmail.com"
description: >-
  A support network for Australian affected by unlawful foreign claims
#baseurl: "" # the subpath of your site, e.g. /blog
#url: "" # the base hostname & protocol for your site, e.g. http://example.com

pagination:
  enabled: true
  per_page: 5
  sort_field: 'date'
  sort_reverse: true

# Build settings
plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-paginate-v2

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - update_boostrap.sh
  - vendor


